

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datos
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class InventarioEntities : DbContext
{
    public InventarioEntities()
        : base("name=InventarioEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Entrada> Entrada { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Proveedor> Proveedor { get; set; }

    public virtual DbSet<Stock> Stock { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }

    public virtual DbSet<DetalleStockFacturacion> DetalleStockFacturacion { get; set; }

    public virtual DbSet<Facturacion> Facturacion { get; set; }

    public virtual DbSet<StockFacturacion> StockFacturacion { get; set; }

}

}

